submit50:
  files: &submit50_files
    - !exclude "*"
    - !include "biasbars.py"
    - !include "rating_stats.py"
    - !include "biasbarsgui.py"
    - !include "biasbarsdata.py"
    - !include "ethics.txt"
  style: false
  
check50:
  files: *submit50_files
